name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: usegrimm.app
      DIST: out
      REGION: us-east-1
      DIST_ID: EOHMAJ2PY9NR8
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Lint the code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Build Static Website
        run: npm run build

      - name: Copy files to the production website with the AWS CLI
        run: aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Cloudfront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths "/*"
